services:
  debugger:
    container_name: debugger-py
    image: ghcr.io/typefox/monaco-languageclient/debugger-py:latest
    build:
      dockerfile: ./packages/examples/resources/debugger/Dockerfile
      context: ../../../..
      # only linux/amd64 for now
      platforms:
        - "linux/amd64"
    platform: linux/amd64
    volumes:
      - ../python:/home/mlc/workspace
      - ../../src/debugger:/home/mlc/server/src
    ports:
      - 55555:5555
    tty: true
    working_dir: /home/mlc/server
    command: [
      "bash", "-c", "npm run start"
    ]
