services:
  clangd-wasm-build:
    image: ghcr.io/typefox/monaco-languageclient/clangd-wasm-build:latest
    build:
      dockerfile: ./build.Dockerfile
      context: .
      # only linux/amd64 for now
      platforms:
        - "linux/amd64"
    platform: linux/amd64
    container_name: clangd-wasm-build
