services:
  clangd-wasm-configure:
    image: ghcr.io/typefox/monaco-languageclient/clangd-wasm-configure:latest
    build:
      dockerfile: ./configure.Dockerfile
      context: .
      # only linux/amd64 for now
      platforms:
        - "linux/amd64"
    platform: linux/amd64
    container_name: clangd-wasm-configure
